### ISSUE TITLE
Add  Matomo iframe

### ISSUE THREAD

**Issue by samu-workopen** [wmde/wikimedia.de#1]
Please add Matamo Iframe. You can search for Matomo in the code. It's above the headline "6.Newsletter"
[Hier Matomo iframe-Code einfügen] (Klick für die Anleitung)

Link to do that
https://matomo.org/docs/privacy/

**Comment by JeroenDeDauw** [comment]
https://github.com/wmde/website/commit/d378b3afc5ef3b2396dde27462858530e9c4636e
