### ISSUE TITLE
Add German Protection Law to the Englisch Site 

### ISSUE THREAD

**Issue by samu-workopen** [wmde/wikimedia.de#2]
When the German Version is okay, I would add the German Protection Law to the englisch Version of the Website until we have a englisch version

**Comment by JeroenDeDauw** [comment]
Is this resolved?

**Comment by samu-workopen** [comment]
Not yet. We have the English Version now & I have to integrate it

**Comment by JeroenDeDauw** [comment]
Is this still relevant?
