### ISSUE TITLE
News section images are not scaled properly

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/wikimedia.de#3]
Example: ![image](https://user-images.githubusercontent.com/146040/40489902-83ddbd0a-5f6a-11e8-9669-9c9e7dabb579.png)

Can be seen at https://staging.wikimedia.de/en

Need to adjust the CSS in such a way that the caption adjusts to the image size

**Comment by JeroenDeDauw** [comment]
Relevant code:

* HTML https://github.com/wmde/website/blob/master/templates/sections/news.html.twig
* CSS https://github.com/wmde/website/blob/master/public/css/components/news.css

**Comment by jdittrich** [comment]
>  that the caption adjusts to the image size

What is the "caption" in this case? I could see none, at least not directly below the picture or so, where captions usually are.

**Comment by JeroenDeDauw** [comment]
Not all images have a caption, see https://staging.wikimedia.de/de for a news section that currently has 2 images with caption.

Example: 
![image](https://user-images.githubusercontent.com/146040/40543829-62cdfafa-6026-11e8-8278-41676bd23943.png)

**Comment by JeroenDeDauw** [comment]
Andrew improved the situation with https://github.com/wmde/wikimedia.de/commit/dac512645dde587dc919199f2df33ed5cd48ab27 though now the license is not always shown on the correct height.

![image](https://user-images.githubusercontent.com/146040/40734785-b15316f8-6439-11e8-9f96-2ef0bbeb308d.png)

![image](https://user-images.githubusercontent.com/146040/40734795-ba34d7c0-6439-11e8-91dd-04b0b3999e71.png)

**Comment by JeroenDeDauw** [comment]
Assuming this is fixed by contractor
